services:
 app:
  image: node:24
  ports:
   - "3000:3000"
  volumes:
   - .:/app
  working_dir: /app
  command: sh -c "npx prisma db push && npm run dev"
  depends_on:
  - postgres
  
 postgres:
  image: postgres:17.5
  ports:
   - "5432:5432"
  environment:
   - POSTGRES_DB=mydb
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=postgres
  volumes:
   - postgres_data:/var/lib/postgresql/data
   
 redis:
  image: redis:latest
  ports:
   - "6379:6379"
  volumes:
   - redis_db:/data
   
volumes:
 postgres_data:
 redis_db: