import express from "express";
import login from "./access/login";
import signup from "./access/signup";
import refresh from "./access/token";
import logout from "./access/logout";
import blog from "./blog/index";
import follow from "./follow/follow";
import createLimiter, { authLimiter } from "../helper/rateLimiter";
const router = express.Router();
const loginLimiter = createLimiter(authLimiter.login);
const signupLimiter = createLimiter(authLimiter.signup);
const logoutLimiter = createLimiter(authLimiter.logout);
router.use("/login", loginLimiter, login);
router.use("/signup", signupLimiter, signup);
router.use("/refresh", refresh);
router.use("/logout", logoutLimiter, logout);
router.use("/blog", blog);
router.use("/follow", follow);
export default router;
